version: '3.4'

services:
  nodeApp:
    image: app
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    environment:
      PORT: 3000
      NODE_ENV: production
    ports:
      - 3000:3000

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: game
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      
  front:
    build:
      context: card-game
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 8080:80